import { Router } from 'express';
import authRoutes from './auth.routes';
import statusRoutes from './status.routes';
import teamRoutes from './team.routes';
import taskRoutes from './task.routes';
import notificationRoutes from './notification.routes';
import commentRoutes from './comment.routes';
import reactionRoutes from './reaction.routes';
import discussionRoutes from './discussion.routes';
import uploadRoutes from './upload.routes';
import apiKeyRoutes from './apiKey.routes';
import chatbotRoutes from './chatbot.routes';
import chatSessionRoutes from './chatSession.routes';
import billingRoutes from './billing.routes';
import integrationsRoutes from './integrations.routes';
import v1Routes from './v1.routes';
import taskTemplateRoutes from './taskTemplate.routes';
import aiRoutes from './ai.routes';
import automationRoutes from './automation.routes';
import auditLogRoutes from './auditLog.routes';
import customFieldRoutes from './customField.routes';
import supportRoutes from './support.routes';
import sharingRoutes from './sharing.routes';
import publicRoutes from './public.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/status', statusRoutes);
router.use('/teams', teamRoutes);
router.use('/tasks', taskRoutes);
router.use('/notifications', notificationRoutes);
router.use('/comments', commentRoutes);
router.use('/reactions', reactionRoutes);
router.use('/discussions', discussionRoutes);
router.use('/uploads', uploadRoutes);
router.use('/api-keys', apiKeyRoutes);
router.use('/chatbots', chatbotRoutes);
router.use('/chat-sessions', chatSessionRoutes);
router.use('/billing', billingRoutes);
router.use('/integrations', integrationsRoutes);
router.use('/v1', v1Routes);
router.use('/templates', taskTemplateRoutes);
router.use('/ai', aiRoutes);
router.use('/automations', automationRoutes);
router.use('/audit', auditLogRoutes);
router.use('/custom-fields', customFieldRoutes);
router.use('/support', supportRoutes);
router.use('/sharing', sharingRoutes);
router.use('/public', publicRoutes);

export default router;
